baseURL = "https://davesmith00000.github.io/fppixels/"
languageCode = "en-gb"
title = "FP Pixels"
# Copyright notice. This is displayer in the footer.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
custom_css = "/static/css/custom.css"
theme = "pickles" # https://github.com/mismith0227/hugo_theme_pickles
googleAnalytics = "UA-129418446-1"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "davidjamessmith"
  github = "davesmith00000"
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  author = "Dave Smith"
  # authorwebsite = "example.com"
  avatar = "/fppixels/images/badge.png"
  # contact = "Your contact link (ex. mailto:foo@example.com)"
  bio = "Principal Software Engineer for the ITV Hub by day, FP games tinkerer by night."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "The train set in my attic."
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about-fp-pixels/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  # [[related.indices]]
  #   name = "keywords"
  #   weight = 150
  #
  # [[related.indices]]
  #   name  = "author"
  #   toLower = true
  #   weight = 30
  #
  # [[related.indices]]
  #   name  = "tags"
  #   weight = 100
  #
  # [[related.indices]]
  #   name  = "date"
  #   weight = 10
  #   pattern = "2017"
